### ISSUE TITLE
[minnn.xyz] 3주차(2019.06.03 ~ 2019.06.09) 할일

### ISSUE THREAD

**Issue by minnnkyeng** [s-eolbaek/dev-junior#10]
####  🍃출퇴근하며 스프링 영상 보기 

- [x] IoC 컨테이너 1부: 스프링 IoC 컨테이너와 빈
- [x] IoC 컨테이너 2부: ApplicationContext와 다양한 빈 설정 방법
- [x] IoC 컨테이너 3부: @Autowire
- [x] IoC 컨테이너 4부: @Component와 컴포넌트 스캔
- [x] IoC 컨테이너 5부: 빈의 스코프
- [x] IoC 컨테이너 6부: Environment 1부. 프로파일
- [x] IoC 컨테이너 6부: Environment 2부. 프로퍼티
- [x] IoC 컨테이너 7부: MessageSource
- [x] IoC 컨테이너 8부: ApplicationEventPublisher
- [x] IoC 컨테이너 9부: ResourceLoader

-----------------------------------------------------------------------------------------------
☑️ 영상 시청 시, [타임스탬프](https://play.google.com/store/apps/details?id=com.artifyapp.timestamp&hl=ko) 앱으로 인증
🚨 벌금 5000원
　
　
👍 스프링으로 웹을 만들 수 있는 그날까지!

**Comment by yourankim** [comment]
💫💫💫

**Comment by s-eolbaek** [comment]
🐤 🐥🐤 🐥

**Comment by minnnkyeng** [comment]
👍 어렵게 모두 해결!
