### ISSUE TITLE
[youran] 4주차 : 2019.06.10 ~ 2019.06.16

### ISSUE THREAD

**Issue by yourankim** [s-eolbaek/dev-junior#12]
## 목표 대상
- 9. 면접문제 : 자료구조 04.트리와 그래프 (1) (149-156쪽)
- 스택과 큐 예제문제 

## 목표 공부량
- 하루 최소 30분 공부하고 내용 or 코드 해 올리기
- 일요일에는 복습 및 정리하는 시간 갖기
- 되도록 하루에 문제 하나는 꼭 풀자.(책에 나온 문제풀이 절차를 지키도록 노력하기)

## 일일목표 예상
- [x] 스택과  문제 1 
- [x] 스택과 큐 문제 2
- [x] 트리의 종류 정리
- [x] 이진 트리 순회 정리
- [x] 이진 힙 정리
- [x] 트라이(접두사 트리) 정리

- 보너스 : 스택과 큐 문제 하나 더

## 혹시라도 시간이 남는다면 이것을 하겠습니다(지난 주에 못해서 재도전)
- 연결리스트 문제 1 관련: 재귀함수 호출시 스택 메모리가 어떻게 돌아가는지 더 알아보자
- git remote, origin 개념

**Comment by minnnkyeng** [comment]
🏃‍♀🏃‍♀🏃‍♀🏃‍♀🏃‍♀

**Comment by s-eolbaek** [comment]
🍉🍉🍉🍉🍉

**Comment by minnnkyeng** [comment]
👍👍👍👍 이번주도 고생하셨습니다!
