### ISSUE TITLE
[s-eolbaek] 4주차(2019.06.10~2019.06.16)

### ISSUE THREAD

**Issue by s-eolbaek** [s-eolbaek/dev-junior#14]
## 05 조건문 switch

- [x] Lesson 01 switch문 소개 ~ Lesson 02 if와 switch 차이점
- [x] Lesson 03 switch 미션

## 이번에 양이 적은 이유...

제가 포폴 정리를 급히 해야해서용 핳.. 이번주만 너그러히.. 부탁드립니다 😚😚😚😚😚😚
다음 주 부터는 또 겁나 달릴거예요... 
물고기를 더욱 화려하게 조종해보겠어요...ㅋㅋㅋ

##  과제 처리 방법

각 레슨 범위 별로 코드나 정리된 내용(텍스트형식)을 제출하는 걸로 과제 완료 처리 할 것임
모두 화이팅..

## 이슈 해결 못했을 경우

5천원  사요나라

**Comment by yourankim** [comment]
ㅋㅋ화이팅..!!! 포폴도 화이팅!!

**Comment by minnnkyeng** [comment]
👍👍👍👍👍 어떤 것을 하든 응원합니다!
