### ISSUE TITLE
[youran] 5주차 : 2019.06.17 ~ 2019.06.23

### ISSUE THREAD

**Issue by yourankim** [s-eolbaek/dev-junior#16]
## 목표 대상
- 9. 면접문제 : 자료구조 04.트리와 그래프 (2) (156-162쪽)
- 트리와 그래프 문제

## 목표 공부량
- 하루 최소 30분 공부하고 내용 or 코드 정리해 올리기
- 일요일에는 복습 및 정리하는 시간 갖기
- 되도록 하루에 문제 하나는 꼭 풀자.(책에 나온 문제풀이 절차를 지키도록 노력하기)

## 일일목표 예상
- [x] 인접리스트 정리 및 구현
- [x] 인접행렬 정리 및 구현
- [x] 그래프 탐색 정리 1
- [x] 그래프 탐색 정리 2(깊이우선탐색)
- [x] 그래프 탐색 정리3(너비우선탐색)
- [x] 그래프탐색 정리4(양방향탐색)
- [x] 트리와 그래프 문제 1

- 보너스 : 트리 구현

**Comment by s-eolbaek** [comment]
🍗 🍖🍗 🍖

**Comment by minnnkyeng** [comment]
👟 👟 👟 👟 👟 👟 👟
