### ISSUE TITLE
s-eolbaek] 5주차(2019.06.17~2019.06.23)

### ISSUE THREAD

**Issue by s-eolbaek** [s-eolbaek/dev-junior#17]
## 06장 반복문 for

- [X] Lesson 01 반복문 소개 ~ 03 단일 for문
- [x] Lesson 04 for문에서 continue문과 break문 ~ 05 다중 for문
- [x] Lesson 06 미션

## 07장 반복문 while

- [x] Lesson 01 while문 소개  ~ Lesson 02 for와 while 차이점
- [x] Lesson 03 while문에소 continue문과 break문 ~ Lesson 04 미션

## 이슈 해결 못했을 경우

5천원  사요나라

**Comment by minnnkyeng** [comment]
👟 👟 👟 👟 👟

**Comment by yourankim** [comment]
🏋️‍♀️🏋️‍♀️🏋️‍♀️🏋️‍♀️🏋️‍♀️🌊🌊🌊

**Comment by s-eolbaek** [comment]
노트북이 병원에 가서 푸쉬를 못했씀다..ㄸㄹㄹ
왜 한박자씩 느리게 입력 되는지 모르겠네용 헤
물고기게임 기필코 만들거여요
