### ISSUE TITLE
[minnn.xyz] 2주차(2019.05.27 ~ 2019.06.02) 할일

### ISSUE THREAD

**Issue by minnnkyeng** [s-eolbaek/dev-junior#3]
#### 📱 출퇴근하며 YOUTUBE 영상보기
- [x] 예제 프로젝트 준비
- [x] 프로젝트 살펴보기
- [x] 프로젝트 과제 풀이
- [x] Inversion of Control
- [x] IoC 컨테이너
- [x] 빈(bean)
- [x] 의존성 주입(Dependency Injection)
- [x] AOP
- [x] 프록시 패턴
- [x] 스프링 @AOP
- [x] 스프링 PSA

🚨 벌금 5000원.....

👍 스프링으로 웹을 만들 수 있는 그날까지!

**Comment by yourankim** [comment]
화
이
팅
🏃‍♀️

**Comment by minnnkyeng** [comment]
1주차(2019.5.20~2019.5.26)를 제대로 지키지 못함에 한탄하며..... 좀 더 현실직시..!  😠

**Comment by s-eolbaek** [comment]
민경언니.. 이슈는 왜이렇게 예쁘죠..?ㅋㅋㅋㅋㅋㅋ  아기자기한 맛이 있달까

**Comment by yourankim** [comment]
지금 보니 범위가 꽤 넓은 것 같다 영상은 어떤 것을 보나요?👩‍💻👨‍🎤🕵️‍♂️

**Comment by minnnkyeng** [comment]
@yourankim  
👩‍💻 📱 https://youtu.be/HACQV_koAIU
이 영상으로 보고 있습니다! 스프링 전반적인 파트 다 설명해주길래 택했습니다!

**Comment by yourankim** [comment]
@minnnkyeng  감사감사..!

**Comment by minnnkyeng** [comment]
📱 출퇴근하며 YOUTUBE 영상보기 ---> 🙆 complete !
