### ISSUE TITLE
[youran] 2주차 (2019.05.27 ~ 2019.06.02)

### ISSUE THREAD

**Issue by yourankim** [s-eolbaek/dev-junior#5]
## 목표 대상
- 9. 면접문제 : 자료구조 02.연결리스트(139-141쪽)
- 시간복잡도 및 자료구조 01, 02 예제문제

## 목표 공부량
- 하루 최소 30분 공부하고 코드 정리해 올리기
- 일요일에는 꼭 정리하는 시간 갖기
- 되도록 하루에 문제 하나는 꼭 풀자.(책에 나온 문제풀이 절차를 지키도록 노력하기)

**Comment by minnnkyeng** [comment]
🏃‍♀🏃‍♀🏃‍♀

**Comment by s-eolbaek** [comment]
🏃‍♀🏃‍♀🏃‍♀
