### ISSUE TITLE
[s-eolbaek] 2주차 (2019.05.27 ~ 2019.06.02)

### ISSUE THREAD

**Issue by s-eolbaek** [s-eolbaek/dev-junior#6]
## 01장 변수

- [x] Lesson 01 변수 소개 ~ 03 변수에 저장할 수 있는 데이터 종류
- [x] Lesson 04 변숫값 저장 및 변경 ~ Lesson 06 변수를 활용한 데이터 중복 제거 및 재사용
- [x] Lesson 07 변수에 어떤 값이 들어 있는지 확인하기 ~ Lesson 10 변수 종류

- [x] Lesson 11 변수 파트 미션 올리기 

## 02장 기본 연산자

- [x] Lesson 01 숫자 연산자 ~ Lesson 05 연산자 우선순위 

- [x] Lesson 06 기본 연산자 미션 올리기 

## 부록 01 초보자를 위한 함수와 클래스

- [x] Lesson 01 초보자를 위한 함수 ~ Lesson 02 초보자를 위한 클래스 

##  과제 처리 방법

각 레슨 범위 별로 코드나 정리된 내용(텍스트형식)을 제출하는 걸로 과제 완료 처리 할 것임
2주차 (2019.05.27 ~ 2019.06.02) 에는 총 6개의 과제 제출이 이뤄져야 합니다..
모두 화이팅..

## 이슈 해결 못했을 경우

저도 거금 5천원을... 낼 것이예요... (절대 내지 않겠어요)

**Comment by minnnkyeng** [comment]
🚴‍♀️🚴‍♀️🚴‍♀️

**Comment by yourankim** [comment]
🎊🎊🎊

**Comment by yourankim** [comment]
멤버변수 코드에 등장하는 prototype은 무슨 역할인가요? 전에도 자바스크립트 소스 보다보면 종종 보이던데 검색도 안해보고 당당하게 질문해봅니다..!

**Comment by s-eolbaek** [comment]
> 멤버변수 코드에 등장하는 prototype은 무슨 역할인가요? 전에도 자바스크립트 소스 보다보면 종종 보이던데 검색도 안해보고 당당하게 질문해봅니다..!

오호... 제가 아는 선에서 답변할게요 부족한 설명일 수 있으니.. 조심..

간단하게 코드로 설명하자면 
```javascript
function Person(){};
var seol = new Person();
```

객체를 만들어질 때 자신을 만드는데 사용된 프로토타입 객체를 이용합니다.

만들어진 객체 안에는 _proto_속성이 있는데 자신을 만들어낸 프로토타입 객체를 참조하는 링크가 있답니다.
seol이라는 객체는 링크를 통해 Person과 연결되어 참조하고있는거죠~
이 숨겨진 링크를 프로토타입이라고 해요 :)

다른 곳에서 예제를 가지고 와봤어용
```javascript
function Person(name) {  
    this.name = name || "혁준"; 
}

 Person.prototype.getName = function(){  
    return this.name;
};
```
![image](https://user-images.githubusercontent.com/50690067/58759781-88d1f700-856a-11e9-843e-f44717e03b00.png)

```javascript
function Korean(name){}  
Korean.prototype = new Person();
// Korean은 Person을 참조(링크,프로토타입)하고 있기때문에
// 상속과 비슷하게 Person의 기능들을 사용가능

var kor1 = new Korean();  
console.log(kor1.getName());  // 혁준

var kor2 = new Korean("지수");  
console.log(kor2.getName()); // 혁준
```


뭔가 질문을 받으니.. 알고 있던 내용도 혼란스러우면서 계속 생각하게 되네요...핳 :) 
(참조:http://www.nextree.co.kr/p7323/)

**Comment by yourankim** [comment]
@s-eolbaek 
친절한 설명 정말 감사..!!! 클래스 개념이 따로 없는 대신 prototype를 참조해서 새 객체도 생성하고 속성도 변경하고 상속도 할 수 있고 그런 역할이라는 거죠? 마지막에 '지수'로 객체 생성했는데 왜 혁준이 나오는지 궁금해서 링크글도 읽어봤는데 역시 알면 알수록 심오한 자바스크립트의 세계...암튼 궁금증이 많이 풀렸어요 고마워욤!!😍

(+)
코드 작성할 때 시작과 끝에 이렇게 써주면 코드 표현이 돼요
\```(키보드에서 1 왼쪽에 있는 키) + 작성언어
코드
\```

(write)
\```javascript
function Person(){};
var seol = new Person();
\```

(preview)
```javascript
function Person(){};
var seol = new Person();
```
