### ISSUE TITLE
[youran] 3주차(2019.06.03 ~ 2019.06.09)

### ISSUE THREAD

**Issue by yourankim** [s-eolbaek/dev-junior#8]
## 목표 대상
- 9. 면접문제 : 자료구조 03.스택과 큐(144-146쪽)
- 연결리스트, 스택과 큐 예제문제 

## 목표 공부량
- 하루 최소 30분 공부하고 코드 정리해 올리기
- 일요일에는 복습 및 정리하는 시간 갖기
- 되도록 하루에 문제 하나는 꼭 풀자.(책에 나온 문제풀이 절차를 지키도록 노력하기)

## 일일목표 예상
- [x] 연결리스트 문제 1 
- [x] 연결리스트 문제 2
- [x] 연결리스트 문제 3
- [x] 연결리스트 문제 4
- [x] 스택과 큐 정리
- [x] 스택과 큐 문제 1
- 보너스 : 스택과 큐 문제 하나 더

## 혹시라도 시간이 남는다면 이것을 하겠습니다
- 연결리스트 문제 1 관련: 재귀함수 호출시 스택 메모리가 어떻게 돌아가는지 더 알아보자
- git remote, origin 개념

**Comment by minnnkyeng** [comment]
🏃‍♀ 🏃‍♀ 🏃‍♀

**Comment by yourankim** [comment]
++ 현충일 믿고 여유 부리다가 막상 현충일이 되니 밀린 거 하기 싫어서 더욱 효율이 떨어지는 (충분히 예상 가능했던) 사태 발생함. 그리고 이건 무슨 문제를 이해하는 것부터가 난관이네요...언제쯤 풀이를 보지 않고 척척 풀 수 있을지..! 달려라 달려🐝🐝🐝🌊🌊🌊🏋️‍♀️🏋️‍♀️🏋️‍♀️🤸‍♂️🤸‍♂️🤸‍♂️⛹️‍♀️⛹️‍♀️⛹️‍♀️⛹️‍♀️🧘‍♂️🧘‍♂️🧘‍♂️

**Comment by s-eolbaek** [comment]
😜😜😜저도 마찬가지인걸료😜😜😜
