### ISSUE TITLE
[s-eolbaek] 3주차 (2019.06.03 ~ 2019.06.09)

### ISSUE THREAD

**Issue by s-eolbaek** [s-eolbaek/dev-junior#9]
## 03장 형변환

- [x] Lesson 01 형변환 소개 ~ 03 명시적 형변환
- [x] Lesson 04 형변환 미션

## 부록 jQuery의 기초

- [x] Lesson 01 jQuery소개 

- [x] Lesson 02 사용법

## 04 조건문 if

- [x] Lesson 01 조건문 소개 ~ Lesson 03 논리 비교 연산자
- [x] Lesson 04 if에 논리 비교 연산자 연동하기 ~ Lesson 07 3단계 if
- [x] Lesson 08 조건부 연산자 ~ Lesson 09 조건문 if 미션

##  과제 처리 방법

각 레슨 범위 별로 코드나 정리된 내용(텍스트형식)을 제출하는 걸로 과제 완료 처리 할 것임
모두 화이팅..

## 이슈 해결 못했을 경우

5천원  사요나라

**Comment by minnnkyeng** [comment]
🏃‍♀ 🏃‍♀ 🏃‍♀

**Comment by yourankim** [comment]
✨✨✨
